"""Hand-written clip archetypes for recreating a groove in a DAW (part of the track-analysis skill).

These are the four clips a recreation session actually needs — four-on-the-floor kick, offbeat
open-hat lane, one sustained chord per bar, rolling bass tucked into the sidechain dip — plus a
transpose. They exist because a whole session's clips were generated by throwaway inline Python
in a shell heredoc: the clips survived in the DAW project, the recipes survived nowhere.

Note times are in BEATS internally and converted at write, so an archetype is tempo-free until it
lands. Every builder takes an explicit `bars` and clamps every note to end inside it: one note
ending 0.006 bars past the 4-bar line made Bitwig size the clip to EIGHT bars with a silent empty
half. That clamp is the whole reason `bars` is an argument rather than something inferred.

Complements midi.py, which exports what a detector *measured*. This writes what a human *decides* —
the move to make when the detector is too polluted to trust (see the --check story in SKILL.md).

Usage: python groove.py --kind four-on-floor --bars 4 --bpm 130.4 --out kick.mid
       python groove.py --kind hats --closed-note 37 --open-note 42 --bars 4 --bpm 130.4 --out hats.mid
       python groove.py --kind chords --voicings 61,68,71:61,66,68 --bars 4 --bpm 130.4 --out chords.mid
       python groove.py --kind bass --note 37 --bars 4 --bpm 130.4 --out bass.mid
Verify before inserting: python midi.py --check-mid <file.mid>
Kick, hats and bass come back 0 FAIL. A chord clip FAILs C2/C3 by construction — those checks read
simultaneous notes as zero-length inter-onset intervals, and they are calibrated for drum lanes.
"""
import argparse
from dataclasses import dataclass, field, replace
from pathlib import Path

import pretty_midi

BPB = 4  # beats per bar; this skill is 4/4 only
HIT = 0.25  # drum note length in beats — long enough to trigger, short enough to never cross a bar line


@dataclass
class Clip:
    """A bar-bounded pattern. `notes` are (start_beats, end_beats, pitch, velocity) from bar 1 beat 1."""
    name: str  # clips inherit the MIDI file's track name, so this is what shows up in the DAW
    bars: int
    is_drum: bool = False
    program: int = 0
    notes: list = field(default_factory=list)
    clamped: int = 0


def _place(clip, start, dur, pitch, vel):
    """Append one note, clamped to die inside the clip. See the module docstring for what an
    overhanging note does to clip length — it is silent corruption, not a rounding detail."""
    end = clip.bars * BPB
    if start >= end - 1e-9:
        clip.clamped += 1
        return
    if start + dur > end:
        clip.clamped += 1
        dur = end - start
    clip.notes.append((start, start + dur, int(pitch), int(max(1, min(127, vel)))))


def four_on_floor(bars, note=36, vel=112, hit=HIT):
    """Kick on every beat, for `bars` bars.

    Written by hand because a detector export once shipped a "four-on-the-floor" lane with no note
    on beat 1 (first hit at beat 0.47) from a window flagged sub_grid_suspect. When the transcription
    is that polluted, writing the pattern the spectrogram plainly shows beats repairing the export.
    """
    c = Clip("kick", bars, is_drum=True)
    for b in range(bars * BPB):
        _place(c, b, hit, note, vel)
    return c


def offbeat_hats(bars, closed_note, open_note, closed_vel=48, open_vel=(112, 118), hit=0.125):
    """Quiet CLOSED hat on each beat, accented OPEN hat on each offbeat 8th.

    closed_note and open_note have NO defaults, deliberately: **the user's kit is not GM until you
    have probed it.** The kit this was built for had only two pads loaded, 37 and 42, with
    **42 = OPEN** and 37 = closed — the reverse of the GM reflex. A GM-shaped clip left every
    offbeat silent and read as "thin" rather than broken, which is the expensive kind of wrong.
    Probe first: one clip per candidate note, relaunch, capture, compare rms — a silent read is
    exactly -240 dBFS. ~10 captures; assuming costs an hour.

    open_vel is a (lo, hi) pair alternated per bar. Identical velocity every bar is what makes a hat
    lane read as a machine, and variation — not timing — is the lever that fixes it (see skills/groove).
    """
    lo, hi = open_vel if isinstance(open_vel, (tuple, list)) else (open_vel, open_vel)
    c = Clip("hats", bars, is_drum=True)
    for bar in range(bars):
        for beat in range(BPB):
            t = bar * BPB + beat
            _place(c, t, hit, closed_note, closed_vel)
            _place(c, t + 0.5, hit, open_note, hi if bar % 2 else lo)
    return c


def sustained_chords(bars, voicings, vel=88, gate=0.97):
    """One chord per bar, held `gate` of the bar. Voicings cycle bar by bar.

    The near-full gate is the point: a chord held the *whole* bar ties into the next one and the
    part stops breathing, while a short stab turns a pad into a rhythm. 0.97 re-articulates every bar.

    The pair this was built for: [61, 68, 71] (C#4/G#4/B4) alternating with [61, 66, 68]
    (C#4/F#4/G#4) — a sus4/b7 colour, deliberately NOT a plain triad; the reference's harmony is
    the suspension, and voicing it as a minor/major triad is the single fastest way to sound wrong.
    """
    c = Clip("chords", bars, program=81)  # 81 = lead/saw; DAWs ignore program, it is documentation
    for bar in range(bars):
        for pitch in voicings[bar % len(voicings)]:
            _place(c, bar * BPB, gate * BPB, pitch, vel)
    return c


def rolling_bass(bars, note, positions16=(1.6, 5.6, 9.6, 13.6), len16=2.4, vel=100):
    """Notes placed just AFTER each beat (16th positions 1.6/5.6/9.6/13.6 = beats 0.4/1.4/2.4/3.4),
    each ~2.4 sixteenths long.

    The lateness is not humanization — it tucks each note into the sidechain dip so the kick owns
    the downbeat and the bass rolls back up as the duck releases. Measure the pump before copying
    these numbers to another track: the offset that works is the one that matches that track's
    release, and 1.6 is where this one's landed.
    """
    c = Clip("bass", bars, program=38)  # synth bass 1, same convention as midi.py's blueprint
    for bar in range(bars):
        for p in positions16:
            _place(c, bar * BPB + p / 4, len16 / 4, note, vel)
    return c


def transpose(clip, semitones):
    """New clip with every pitch shifted. A preset that SOUNDS an octave below the written pitch
    needs the clip moved, not the patch — but verify the sounding pitch by capture first (fit the
    whole harmonic series, not the loudest peak). A -12 applied to an octave-error reading
    transposes a correct clip into the wrong octave, and it sounds plausible either way.
    """
    return replace(clip, notes=[(s, e, max(0, min(127, p + semitones)), v) for s, e, p, v in clip.notes])


def write(clip, path, bpm):
    """Write the clip and read it back; print note count, pitches and the true end in bars.

    The read-back is not ceremony: tick rounding at write is the last place a note can slip past the
    bar line, and the printed end is what the DAW will size the clip to.
    """
    pm = pretty_midi.PrettyMIDI(initial_tempo=bpm)
    inst = pretty_midi.Instrument(program=clip.program, is_drum=clip.is_drum, name=clip.name)
    spb = 60.0 / bpm
    for s, e, p, v in sorted(clip.notes):
        inst.notes.append(pretty_midi.Note(velocity=v, pitch=p, start=s * spb, end=e * spb))
    pm.instruments.append(inst)
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    pm.write(str(path))
    back = pretty_midi.PrettyMIDI(str(path))
    ends = [back.time_to_tick(n.end) / back.resolution / BPB for i in back.instruments for n in i.notes]
    end = max(ends, default=0.0)
    pitches = sorted({p for _, _, p, _ in clip.notes})
    print(f"{path}: {len(clip.notes)} notes, pitches {pitches}, ends {end:.4f} of {clip.bars} bars"
          f" @ {bpm:g} BPM, track \"{clip.name}\"{', drum' if clip.is_drum else ''}"
          + (f", {clip.clamped} clamped" if clip.clamped else ""))
    if end > clip.bars + 1e-6:
        print(f"  OVERHANG {end - clip.bars:.4f} bars — the DAW will double the clip length; do not insert")
    return end


def _ints(s, sep=","):
    return [int(x) for x in s.split(sep) if x.strip()]


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--kind", required=True, choices=["four-on-floor", "hats", "chords", "bass"])
    ap.add_argument("--bars", type=int, default=4)
    ap.add_argument("--bpm", type=float, required=True, help="written into the file; match the analyzed BPM")
    ap.add_argument("--out", required=True)
    ap.add_argument("--name", help="MIDI track name — the DAW names the clip after it")
    ap.add_argument("--transpose", type=int, default=0, help="semitones, applied last (see transpose())")
    ap.add_argument("--note", type=int, help="four-on-floor: kick note (36); bass: pitch")
    ap.add_argument("--vel", type=int, help="four-on-floor 112 / chords 88 / bass 100")
    ap.add_argument("--closed-note", type=int, help="hats: PROBE THE KIT, no GM default")
    ap.add_argument("--open-note", type=int, help="hats: PROBE THE KIT — one session's kit had 42 = OPEN")
    ap.add_argument("--closed-vel", type=int, default=48)
    ap.add_argument("--open-vel", default="112,118", help="hats: lo,hi accent alternated per bar")
    ap.add_argument("--voicings", default="61,68,71:61,66,68", help="chords: colon-separated, e.g. 61,68,71:61,66,68")
    ap.add_argument("--gate", type=float, default=0.97, help="chords: held fraction of the bar")
    ap.add_argument("--positions16", default="1.6,5.6,9.6,13.6", help="bass: 16th positions within the bar")
    ap.add_argument("--len16", type=float, default=2.4, help="bass: note length in 16ths")
    a = ap.parse_args()

    if a.kind == "four-on-floor":
        clip = four_on_floor(a.bars, note=a.note or 36, vel=a.vel or 112)
    elif a.kind == "hats":
        if a.closed_note is None or a.open_note is None:
            ap.error("--closed-note and --open-note are required: probe the kit, do not assume GM")
        clip = offbeat_hats(a.bars, a.closed_note, a.open_note, closed_vel=a.closed_vel,
                            open_vel=tuple(_ints(a.open_vel))[:2])
    elif a.kind == "chords":
        clip = sustained_chords(a.bars, [_ints(v) for v in a.voicings.split(":")], vel=a.vel or 88, gate=a.gate)
    else:
        if a.note is None:
            ap.error("--note is required for bass")
        clip = rolling_bass(a.bars, a.note, positions16=[float(x) for x in a.positions16.split(",")],
                            len16=a.len16, vel=a.vel or 100)
    if a.transpose:
        clip = transpose(clip, a.transpose)
    if a.name:
        clip = replace(clip, name=a.name)
    write(clip, a.out, a.bpm)
